// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type NewPing struct {
	Timestamp time.Time `json:"timestamp"`
}

type Ping struct {
	ID        string     `json:"id"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
